<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MetroPulse.Domain</RootNamespace>
    <AssemblyName>MetroPulse.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../src/data/missions.json"
                      Link="Content/missions.json"
                      LogicalName="MetroPulse.Domain.Content.missions.json" />
  </ItemGroup>
</Project>
