import {
  CATALOG_STAGES,
  CONSTRUCTION_CATEGORIES,
  getCatalogAccess,
  isCatalogSpecDisclosed,
  PROGRESSION_TIERS
} from './ConstructionVocabulary.js';

export const BUILDING_CATEGORIES = CONSTRUCTION_CATEGORIES;

export const BUILDING_CATALOG = [
  // Commercial
  {
    id: 'NEOTECH_HQ',
    name: 'NeoTech Quantum Tower',
    category: 'COMMERCIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.MAGNATE,
    icon: '🏢',
    description: 'High-tech AI and robotics research tower with neon cyber accents and rooftop landing pad.',
    footprint: { width: 40, depth: 40 },
    height: 75,
    cost: 750000,
    value: 960000,
    status: 'Operational',
    baseColor: 0x3b4d68,
    accentColor: 0x00f0ff,
    generatorType: 'SKYSCRAPER',
    employees: 1420,
    incomePerMinute: 9800,
    powerDemand: 18,
    waterDemand: 12,
    happiness: 2,
    specialty: 'Quantum AI & Robotics'
  },
  {
    id: 'APEX_BANK',
    name: 'Apex Financial Spire',
    category: 'COMMERCIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.MAGNATE,
    icon: '🏦',
    description: 'Decentralized financial headquarters featuring golden architectural ribs and corporate beacon.',
    footprint: { width: 44, depth: 44 },
    height: 85,
    cost: 650000,
    value: 845000,
    status: 'Operational',
    baseColor: 0x475569,
    accentColor: 0xffaa00,
    generatorType: 'SKYSCRAPER',
    employees: 980,
    incomePerMinute: 8200,
    powerDemand: 15,
    waterDemand: 9,
    happiness: 1,
    specialty: 'Decentralized Crypto Banking'
  },
  {
    id: 'CYBERCAFE',
    name: 'CyberCafe 24/7',
    category: 'COMMERCIAL',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '☕',
    description: 'Bustling cyber cafe with glowing magenta canopy and high-speed quantum network access.',
    footprint: { width: 30, depth: 30 },
    height: 25,
    cost: 200000,
    value: 265000,
    status: 'Operational',
    baseColor: 0x5a3e73,
    accentColor: 0xff00ff,
    generatorType: 'SHOP',
    signText: '☕ CYBERCAFE',
    employees: 35,
    incomePerMinute: 2400,
    powerDemand: 5,
    waterDemand: 4,
    happiness: 3,
    specialty: 'High-Speed Gaming & Coffee'
  },
  {
    id: 'GALAXY_CINEMA',
    name: 'Galaxy Hologram Cinema',
    category: 'COMMERCIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🎬',
    description: 'Futuristic multiplex displaying immersive 3D holographic movie experiences.',
    footprint: { width: 36, depth: 36 },
    height: 35,
    cost: 420000,
    value: 560000,
    status: 'Operational',
    baseColor: 0x4f3f6e,
    accentColor: 0xffb800,
    generatorType: 'SHOP',
    signText: '🎬 GALAXY CINEMA',
    employees: 85,
    incomePerMinute: 3900,
    powerDemand: 9,
    waterDemand: 5,
    happiness: 6,
    specialty: 'Immerse-3D Hologram Movies'
  },

  // Residential
  {
    id: 'SKYLINE_CONDOS',
    name: 'Skyline Luxury Condos',
    category: 'RESIDENTIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🏙️',
    description: 'Multi-tiered residential skyscraper with wraparound panoramic glass balconies.',
    footprint: { width: 36, depth: 36 },
    height: 55,
    cost: 500000,
    value: 690000,
    status: 'Occupied',
    baseColor: 0x3d4a5c,
    accentColor: 0x44ddaa,
    generatorType: 'RESIDENTIAL',
    residents: 340,
    incomePerMinute: 3100,
    powerDemand: 13,
    waterDemand: 16,
    happiness: 2,
    specialty: 'Skyline Residential Living'
  },
  {
    id: 'METRO_LOFTS',
    name: 'Metro Cyber Lofts',
    category: 'RESIDENTIAL',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '🏬',
    description: 'Contemporary urban residential lofts designed for metropolitan living.',
    footprint: { width: 30, depth: 30 },
    height: 38,
    cost: 350000,
    value: 470000,
    status: 'Occupied',
    baseColor: 0x4e4e58,
    accentColor: 0x66ccff,
    generatorType: 'RESIDENTIAL',
    residents: 180,
    incomePerMinute: 1900,
    powerDemand: 8,
    waterDemand: 10,
    happiness: 1,
    specialty: 'Urban Cyber Lofts'
  },
  {
    id: 'GARDEN_TOWER',
    name: 'Eco-Spire Garden Tower',
    category: 'RESIDENTIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🌿',
    description: 'Sustainable vertical garden complex with illuminated terrace gardens and clean energy systems.',
    footprint: { width: 38, depth: 38 },
    height: 68,
    cost: 480000,
    value: 670000,
    status: 'Occupied',
    baseColor: 0x2e5a44,
    accentColor: 0x44ff88,
    generatorType: 'RESIDENTIAL',
    residents: 520,
    incomePerMinute: 4200,
    powerDemand: 11,
    waterDemand: 14,
    happiness: 7,
    specialty: 'Vertical Eco-Living'
  },

  // Civic & Medical
  {
    id: 'MED_CENTER',
    name: 'Bio-Regen Medical Center',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🏥',
    description: 'State-of-the-art cybernetic emergency medical hospital and trauma recovery center.',
    footprint: { width: 42, depth: 42 },
    height: 45,
    cost: 400000,
    value: 535000,
    status: 'Operational',
    baseColor: 0xeeeeee,
    accentColor: 0xff3344,
    generatorType: 'CIVIC',
    signText: '🏥 BIO-REGEN MEDICAL',
    employees: 310,
    incomePerMinute: -1700,
    powerDemand: 12,
    waterDemand: 11,
    happiness: 8,
    specialty: 'Emergency Cyber Trauma Care'
  },
  {
    id: 'CYBER_POLICE',
    name: 'Metro Peacekeeping Precinct',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🚓',
    description: 'Metropolitan police precinct equipped with drone launch bays and security command array.',
    footprint: { width: 34, depth: 34 },
    height: 30,
    cost: 320000,
    value: 420000,
    status: 'Operational',
    baseColor: 0x2c3e50,
    accentColor: 0x3498db,
    generatorType: 'CIVIC',
    signText: '🚓 METRO PRECINCT',
    employees: 140,
    incomePerMinute: -1250,
    powerDemand: 7,
    waterDemand: 4,
    fireCoverage: 5,
    happiness: 3,
    specialty: 'City Peacekeeping & Drones'
  },
  {
    id: 'SOLAR_PLAZA',
    name: 'Cyber Plaza & Fountain',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '⛲',
    description: 'Public park and gathering plaza featuring glowing bio-trees and a illuminated water fountain.',
    footprint: { width: 40, depth: 40 },
    height: 8,
    cost: 150000,
    value: 235000,
    status: 'Open',
    baseColor: 0x224433,
    accentColor: 0x00ffcc,
    generatorType: 'PARK_PLAZA',
    incomePerMinute: -250,
    powerDemand: 2,
    waterDemand: 3,
    happiness: 12,
    amenityRadius: 95,
    specialty: 'Public Leisure & Recreation'
  },

  // Infrastructure & Utilities
  {
    id: 'ROAD_STRAIGHT',
    name: 'Asphalt Road Segment',
    category: 'INFRASTRUCTURE',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '🛣️',
    description: 'Standard 30m asphalt roadway with glowing lane dividers and sidewalk curbs.',
    footprint: { width: 30, depth: 30 },
    height: 1,
    cost: 25000,
    value: 25000,
    status: 'Open',
    baseColor: 0x24272c,
    accentColor: 0xffffaa,
    generatorType: 'ROAD_SEGMENT',
    incomePerMinute: -80,
    roadType: 'STRAIGHT',
    specialty: 'Vehicle Road Network'
  },
  {
    id: 'ROAD_INTERSECTION',
    name: '4-Way Road Crossing',
    category: 'INFRASTRUCTURE',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '➕',
    description: 'Four-way intersection junction connecting urban road blocks with crosswalks.',
    footprint: { width: 30, depth: 30 },
    height: 1,
    cost: 35000,
    value: 35000,
    status: 'Open',
    baseColor: 0x24272c,
    accentColor: 0x00ffff,
    generatorType: 'ROAD_SEGMENT',
    incomePerMinute: -110,
    roadType: 'INTERSECTION',
    specialty: 'Traffic Junction'
  },
  {
    id: 'SOLAR_GRID',
    name: 'Quantum Energy Array',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '⚡',
    description: 'High-output solar and zero-point energy generation station powering the city.',
    footprint: { width: 26, depth: 26 },
    height: 15,
    cost: 280000,
    value: 360000,
    status: 'Online',
    baseColor: 0x1a2b3c,
    accentColor: 0x00ffaa,
    generatorType: 'ENERGY_ARRAY',
    incomePerMinute: -450,
    powerSupply: 90,
    waterDemand: 2,
    happiness: 2,
    specialty: 'Clean Power Grid'
  },

  // Industrial & logistics
  {
    id: 'CYBER_FAB',
    name: 'Titan Cyber-Fabrication Works',
    category: 'OPERATIONS',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '🏭',
    description: 'Automated fabrication campus producing transit components and corporate-grade consumer optimism.',
    footprint: { width: 44, depth: 44 },
    height: 32,
    cost: 390000,
    value: 510000,
    status: 'Operational',
    baseColor: 0x3b4148,
    accentColor: 0xff7a18,
    generatorType: 'INDUSTRIAL',
    employees: 430,
    incomePerMinute: 6200,
    powerDemand: 22,
    waterDemand: 15,
    happiness: -4,
    specialty: 'Autonomous Heavy Manufacturing'
  },
  {
    id: 'ORBITAL_LOGISTICS',
    name: 'Orbital Logistics Exchange',
    category: 'OPERATIONS',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '🚚',
    description: 'River-crossing freight exchange serving Orbital Systems and the east-bank corporate arcology.',
    footprint: { width: 40, depth: 40 },
    height: 24,
    cost: 310000,
    value: 420000,
    status: 'Operational',
    baseColor: 0x334155,
    accentColor: 0x38bdf8,
    generatorType: 'INDUSTRIAL',
    employees: 260,
    incomePerMinute: 4700,
    powerDemand: 14,
    waterDemand: 8,
    happiness: -1,
    specialty: 'Cross-District Freight Routing'
  },

  // Utilities & emergency services
  {
    id: 'WATER_RECLAMATION',
    name: 'AquaLoop Reclamation Hub',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.BROKER,
    icon: '💧',
    description: 'Closed-loop municipal water treatment and distribution plant.',
    footprint: { width: 34, depth: 34 },
    height: 18,
    cost: 260000,
    value: 335000,
    status: 'Online',
    baseColor: 0x164e63,
    accentColor: 0x22d3ee,
    generatorType: 'UTILITY',
    employees: 75,
    incomePerMinute: -500,
    powerDemand: 9,
    waterSupply: 100,
    happiness: 2,
    specialty: 'Water Purification & Distribution'
  },
  {
    id: 'FIRE_STATION',
    name: 'Phoenix Fire & Rescue',
    category: 'FACILITIES',
    catalogStage: CATALOG_STAGES.STARTER,
    progressionTier: PROGRESSION_TIERS.OPERATOR,
    icon: '🚒',
    description: 'Rapid-response fire service protecting buildings from infrastructure and Mayhem hazards.',
    footprint: { width: 32, depth: 32 },
    height: 22,
    cost: 295000,
    value: 380000,
    status: 'Ready',
    baseColor: 0x7f1d1d,
    accentColor: 0xfbbf24,
    generatorType: 'CIVIC',
    signText: '🚒 PHOENIX FIRE',
    employees: 95,
    incomePerMinute: -900,
    powerDemand: 5,
    waterDemand: 5,
    fireCoverage: 45,
    happiness: 7,
    specialty: 'Emergency Fire Response'
  },
  {
    id: 'BRIDGE_DECK',
    name: 'Smart Bridge Deck Segment',
    category: 'INFRASTRUCTURE',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.MAGNATE,
    icon: '🌉',
    description: 'Reinforced smart-lane deck segment with adaptive congestion signage.',
    footprint: { width: 30, depth: 30 },
    height: 2,
    cost: 95000,
    value: 105000,
    status: 'Open',
    baseColor: 0x334155,
    accentColor: 0x00f0ff,
    generatorType: 'ROAD_SEGMENT',
    roadType: 'BRIDGE',
    incomePerMinute: -180,
    trafficCapacity: 12,
    specialty: 'Cross-River Traffic Capacity'
  },
  {
    id: 'AETHER_LANDMARK',
    name: 'Aether Prosperity Beacon',
    category: 'COMMERCIAL',
    catalogStage: CATALOG_STAGES.ADVANCED,
    progressionTier: PROGRESSION_TIERS.MAGNATE,
    icon: '🌆',
    description: 'Prestige landmark broadcasting that quarterly growth is a civic virtue.',
    footprint: { width: 46, depth: 46 },
    height: 110,
    cost: 980000,
    value: 1450000,
    status: 'Operational',
    baseColor: 0x312e81,
    accentColor: 0xe879f9,
    generatorType: 'SKYSCRAPER',
    employees: 1800,
    incomePerMinute: 14500,
    powerDemand: 25,
    waterDemand: 12,
    happiness: 8,
    amenityRadius: 120,
    specialty: 'Corporate Landmark & District Prestige'
  }
];

export function getCatalogByCategory(category, {
  includeAdvanced = true,
  progression = {},
  includeLocked = true
} = {}) {
  return BUILDING_CATALOG.filter(item => (
    (!category || category === 'ALL' || item.category === category)
    && isCatalogSpecDisclosed(item, { includeAdvanced })
    && (includeLocked || getCatalogAccess(item, progression).unlocked)
  ));
}

export function getBuildingSpec(id) {
  return BUILDING_CATALOG.find(item => item.id === id) || null;
}

export function getDefaultBuildingSpec() {
  return BUILDING_CATALOG.find(item => item.catalogStage === CATALOG_STAGES.STARTER) || null;
}

export { getCatalogAccess };
